# nixpacks.toml
[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python src/irs_bot/server.py"

[variables]
PORT = "8000"
